### ISSUE TITLE
[Feature Request] prefers-color-scheme

### ISSUE THREAD

**Issue by Mennaruuk** [ViewTube/viewtube#352]
### Description
Hello! I was wondering if `prefers-color-scheme` could be implemented in ViewTube, even if as an opt in. If enabled, ViewTube would check for system theme and switch to either light or dark mode. GitHub has something similar to this, and DuckDuckGo uses `prefers-color-scheme`. Thank you!

**Comment by mauriceoegerli** [comment]
There is a theme editor currently being worked on. I will check if this can be implemented there.

**Comment by Mennaruuk** [comment]
Thanks a lot @mauriceoegerli, appreciate your hard work!!

**Comment by moisout** [comment]
This has now been implemented in release 0.14.0!
(After over 2 years xD)
